"""Supplier Radar operator CLI.

  python -m app.cli ingest organizer /data/raw [--dry-run] [--force] [--reset-organizer-data]
  python -m app.cli ingest-status
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import psycopg

from app.ingestion import organizer
from app.shared.config import database_url, repo_root


def _cmd_ingest(args) -> int:
    if args.source != "organizer":
        print(f"unknown source {args.source!r}", file=sys.stderr)
        return 2
    try:
        report = organizer.ingest_organizer(database_url(), Path(args.raw_dir), dry_run=args.dry_run, force=args.force,
                                            reset=args.reset_organizer_data, reports_dir=None if args.dry_run else repo_root() / "reports")
    except organizer.IngestionError as e:
        print(f"INGESTION STOPPED: {e}", file=sys.stderr)
        return 1
    if args.dry_run:
        print(json.dumps(report, indent=1, sort_keys=True))
        return 0
    meta = report["meta"]
    print(json.dumps({"mode": meta["mode"], "reconciliation": report["reconciliation"], "counts": report["counts"],
                      "failed_checks": [k for k, c in report["checks"].items() if not c["ok"]],
                      "total_seconds": meta["total_seconds"]}, indent=1, ensure_ascii=False))
    return 0 if report["reconciliation"] == "PASS" else 1


def _cmd_status(_args) -> int:
    with psycopg.connect(database_url()) as conn:
        deliveries = conn.execute("""SELECT delivery_id::text, normalization_version, completed_at::text
                                     FROM ingestion_delivery ORDER BY completed_at""").fetchall()
        rec = organizer.reconcile(conn)
    print(json.dumps({"deliveries": deliveries, "reconciliation": rec["reconciliation"], "counts": rec["counts"],
                      "failed_checks": {k: c for k, c in rec["checks"].items() if not c["ok"]}},
                     indent=1, ensure_ascii=False, default=str))
    return 0 if rec["reconciliation"] == "PASS" else 1


def _benchmark_report(stats: dict, validation: dict | None, files: dict | None, runtime: float) -> None:
    from app.benchmark import temporal as T
    reports = repo_root() / "reports"
    det = {"generator_version": T.GENERATOR_VERSION, "benchmark_version": T.BENCHMARK_VERSION, "statistics": stats,
           "excluded_golden_lots": sorted(T.GOLDEN_LOTS),
           "determinism_sha256": {n: hashlib.sha256(d).hexdigest() for n, d in sorted((files or {}).items())},
           "validation": validation}
    (reports / "benchmark_seed_report.json").write_text(json.dumps(det, ensure_ascii=False, indent=1, sort_keys=True, default=str) + "\n",
                                                        encoding="utf-8")
    (reports / "benchmark_seed_report.meta.json").write_text(json.dumps({"runtime_seconds": runtime}, indent=1) + "\n", encoding="utf-8")
    lines = ["# Temporal Replay Benchmark — Seed Report (P1-001E)", "",
             f"> Generated by `python -m app.cli benchmark generate` · generator {T.GENERATOR_VERSION} · benchmark {T.BENCHMARK_VERSION} · "
             f"runtime {runtime} s. Files: `benchmark/replay/`. Labels: 2 = observed winner, 1 = observed non-winner, unjudged = not observed "
             "(**not** irrelevant).", ""]
    if validation:
        lines += [f"**Validation: {'PASS' if validation['passed'] else 'FAIL'}**", ""]
        lines += [f"- {'✅' if ok else '❌'} {k}" for k, ok in validation["checks"].items()]
        lines += ["", f"- Leakage probe: {validation['leakage_probe']}", ""]
    lines += ["## Eligible population", "| Split | Eligible | Participants | Multi-item % | Multi-OKPD2 % |", "|---|---:|---|---:|---:|"]
    for sp, p in stats["population"].items():
        lines.append(f"| {sp} | {p['eligible']:,} | {p['participants']} | {p['multi_item_pct']} | {p['multi_okpd2_pct']} |")
    lines += ["", "## Selected queries", "| Split | Queries | Qrels | Qrels/query | Grade 2 | Grade 1 | Multi-winner | Difficulty | "
              "Winner seen: any / same OKPD2 / same group / same customer (%) | Multi-item % | Multi-OKPD2 % | Generic title % |",
              "|---|---:|---:|---:|---:|---:|---:|---|---|---:|---:|---:|"]
    for sp, s in stats["splits"].items():
        lines.append(f"| {sp} | {s['queries']} | {s['qrels']} | {s['qrels_per_query']} | {s['grade_2']} | {s['grade_1']} | "
                     f"{s['multi_winner_queries']} | {s['difficulty']} | {s['winner_seen_before_anywhere_pct']} / {s['winner_seen_same_okpd2_pct']} / "
                     f"{s['winner_seen_same_okpd2_group_pct']} / {s['winner_seen_same_customer_pct']} | {s['multi_item_pct']} | "
                     f"{s['multi_okpd2_pct']} | {s['generic_title_pct']} |")
    lines += ["", "## OKPD2 strata (section letter / MULTI / NONE)"]
    for sp, s in stats["splits"].items():
        lines.append(f"- **{sp}** selected: {s['okpd2_strata']} · eligible: {stats['population'][sp]['strata']}")
    lines += ["", "## Participants per query (selected)"] + [f"- {sp}: {s['participants']}" for sp, s in stats["splits"].items()]
    lines += ["", f"Excluded golden lots: {', '.join(sorted(T.GOLDEN_LOTS))}", "",
              "Determinism (sha256): " + ", ".join(f"`{n}` {h[:16]}…" for n, h in det["determinism_sha256"].items()), ""]
    (reports / "benchmark_seed_report.md").write_text("\n".join(lines), encoding="utf-8")


def _cmd_golden(args) -> int:
    from app.benchmark import golden as G
    out = repo_root() / "benchmark" / "golden"
    with psycopg.connect(database_url()) as conn:
        if args.action == "golden":
            G.write(G.build(conn), out)
        result = G.validate(conn, out, repo_root() / "benchmark" / "replay" / "queries.csv")
    print(json.dumps(result, indent=1))
    return 0 if result["passed"] else 1


def _cmd_benchmark(args) -> int:
    import time
    from app.benchmark import temporal as T
    if args.action in ("golden", "golden-validate"):
        return _cmd_golden(args)
    out = repo_root() / "benchmark" / "replay"
    t0 = time.perf_counter()
    with psycopg.connect(database_url()) as conn:
        if args.action == "generate":
            b, files = T.generate(conn, out, seed=args.seed)
            validation = T.validate(conn, out, regenerate=True)
            stats = T.statistics(b)
        else:
            validation = T.validate(conn, out, regenerate=True)
            b = T.build(conn, seed=json.loads((out / "manifest.json").read_text(encoding="utf-8"))["sampling_seed"])
            stats, files = T.statistics(b), {n: (out / n).read_bytes() for n in ("queries.csv", "qrels.csv", "query_metadata.csv", "manifest.json")}
    runtime = round(time.perf_counter() - t0, 1)
    _benchmark_report(stats, validation, files, runtime)
    print(json.dumps({"validation": "PASS" if validation["passed"] else "FAIL",
                      "failed": [k for k, ok in validation["checks"].items() if not ok],
                      "queries": {sp: s["queries"] for sp, s in stats["splits"].items()},
                      "leakage_probe": validation["leakage_probe"], "runtime_seconds": runtime}, indent=1))
    return 0 if validation["passed"] else 1


def _cmd_search(args) -> int:
    from app.search import stats
    with psycopg.connect(database_url()) as conn:
        print(json.dumps(stats.build(conn), indent=1))
    return 0


def _cmd_recommend(args) -> int:
    from datetime import date
    from app.search.models import DEFAULT_CONFIG
    from app.search.recommend import recommend
    cfg = DEFAULT_CONFIG.with_(top_k=args.top_k)
    with psycopg.connect(database_url()) as conn:
        out = recommend(conn, args.lot_id, cfg, date.fromisoformat(args.as_of) if args.as_of else None)
    if not args.explain:
        for r in out["results"]:
            r.pop("reasons", None)
    print(json.dumps(out, indent=1, ensure_ascii=False, default=str))
    return 0


def _cmd_evaluate(args) -> int:
    from app.search import report
    from app.search.report_md import render_md
    out = repo_root() / "reports"
    if args.what == "ranking-diagnostics":
        from app.search import ranking_study as RS
        with psycopg.connect(database_url()) as conn:
            d = RS.run_diagnostics(conn, log=lambda m: print(f"[diag] {m}", file=sys.stderr, flush=True))
        (out / "p2_003_ranking_diagnostics.json").write_text(json.dumps(d, ensure_ascii=False, indent=1, sort_keys=True, default=str)
                                                             + chr(10), encoding="utf-8")
        print(json.dumps({k: d[k] for k in ("baseline_reproduced", "conditional_baseline", "query_groups", "dominant_cause_counts",
                                            "mean_contribution_deficit_vs_suppliers_above", "share_of_above_suppliers_with_higher_component",
                                            "evidence_shape_winner_vs_top10_mean (medians over failures)", "query_flags")},
                         indent=1, ensure_ascii=False))
        return 0
    if args.what == "ranking":
        from app.search import ranking_experiments as RX
        with psycopg.connect(database_url()) as conn:
            r = RX.run(conn, log=lambda m: print(f"[rank] {m}", file=sys.stderr, flush=True))
        (out / "p2_003_ranking.json").write_text(json.dumps(r, ensure_ascii=False, indent=1, sort_keys=True, default=str) + chr(10),
                                                encoding="utf-8")
        print(json.dumps({"chosen": r["chosen"]["name"], "accepted": r["accepted_challengers"],
                          "latency": r["latency_dev_end_to_end_chosen"]}, indent=1, ensure_ascii=False))
        return 0
    if args.what == "ranking-report":
        from app.search.report_p2_003 import render_diagnostics, render_ranking
        d = json.loads((out / "p2_003_ranking_diagnostics.json").read_text(encoding="utf-8"))
        (out / "p2_003_ranking_diagnostics.md").write_text(render_diagnostics(d), encoding="utf-8")
        r = json.loads((out / "p2_003_ranking.json").read_text(encoding="utf-8"))
        (out / "p2_003_ranking.md").write_text(render_ranking(r), encoding="utf-8")
        return 0
    if args.what == "baseline-report":
        r = json.loads((out / "p1_002_baseline.json").read_text(encoding="utf-8"))
        (out / "p1_002_baseline.md").write_text(render_md(r), encoding="utf-8")
        return 0
    with psycopg.connect(database_url()) as conn:
        result = report.run(conn, log=lambda m: print(f"[eval] {m}", file=sys.stderr, flush=True))
    (out / "p1_002_baseline.json").write_text(json.dumps(result, ensure_ascii=False, indent=1, sort_keys=True, default=str) + "\n",
                                             encoding="utf-8")
    (out / "p1_002_baseline.md").write_text(render_md(result), encoding="utf-8")
    print(json.dumps({"chosen": result["chosen_configuration"]["name"], "dev": result["dev"]["unweighted"],
                      "latency": result["latency_dev_end_to_end"]}, indent=1))
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="python -m app.cli")
    sub = ap.add_subparsers(dest="cmd", required=True)
    ing = sub.add_parser("ingest", help="load a source into PostgreSQL")
    ing.add_argument("source", choices=["organizer"])
    ing.add_argument("raw_dir")
    ing.add_argument("--dry-run", action="store_true", help="verify hashes/headers and normalize everything; write nothing")
    ing.add_argument("--force", action="store_true", help="re-process an already loaded delivery (idempotent: inserts 0 rows)")
    ing.add_argument("--reset-organizer-data", action="store_true",
                     help="delete organizer-derived raw/canonical rows and manifests first (enrichment rows are kept)")
    ing.set_defaults(func=_cmd_ingest)
    st = sub.add_parser("ingest-status", help="read-only reconciliation of the loaded organizer data")
    st.set_defaults(func=_cmd_status)
    bm = sub.add_parser("benchmark", help="temporal replay benchmark (P1-001E)")
    bm.add_argument("action", choices=["generate", "validate", "golden", "golden-validate"])
    bm.add_argument("--seed", type=int, default=20261001)
    bm.set_defaults(func=_cmd_benchmark)
    se = sub.add_parser("search", help="search support data")
    se.add_argument("action", choices=["build-stats"])
    se.set_defaults(func=_cmd_search)
    rc = sub.add_parser("recommend", help="baseline supplier recommendation for an existing lot (P1-002)")
    rc.add_argument("kind", choices=["lot"])
    rc.add_argument("lot_id")
    rc.add_argument("--top-k", type=int, default=10)
    rc.add_argument("--as-of", help="YYYY-MM-DD; default = the lot's publish_date (history strictly before it)")
    rc.add_argument("--explain", action="store_true")
    rc.set_defaults(func=_cmd_recommend)
    ev = sub.add_parser("evaluate", help="evaluate the P1-002 baseline on WARM-UP + DEV (holdout sealed)")
    ev.add_argument("what", choices=["baseline", "baseline-report", "ranking-diagnostics", "ranking", "ranking-report"])
    ev.set_defaults(func=_cmd_evaluate)
    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
